### ISSUE TITLE
Add input validation for component names

### ISSUE THREAD

**Issue by Zaperex** [janus-idp/software-templates#172]
### What needs to be done?
We need to add input validation for the component name inputs to ensure they satisfy the default format specified in the [`backstage architectural decisions docs`](https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md#name): 
- Strings of length at least 1, and at most 63 (from testing, it's observed that it should actually be at most 62 chars)
- Must consist of sequences of [a-z0-9A-Z] possibly separated by one of [-_.]

For this default format, we will need to add the following pattern validation for the input field: 
```yaml
properties:
  <propertyName>:
    title: Component Name
    type: string
    pattern: "^[a-z0-9A-Z-_.]+$"
    maxLength: 62
```
The 62 maxLength is because the catalog appears to actually not accept names that are 63 characters long.

- Tested with `c0mponent-name_1234567890.abcdefghijklmnopqrstuvwxyz-abcdefghi_` which is exactly 63 chars long, but it got rejected.

- Tested with `c0mponent-name_1234567890.abcdefghijklmnopqrstuvwxyz-abcdefghi`, and it was accepted and ingested into the catalog/
